---
- hosts: 127.0.0.1
  tasks:
    - name: check if there are any changes
      command: git status --porcelain chdir="{{ projects_path }}"
      register: status_result

    - name: add changes
      command: git add --all chdir="{{ projects_path }}"
      when: status_result.stdout != ""

    - name: commit
      command: git commit -m "{{ commit_msg }}" chdir="{{ projects_path }}"
      when: status_result.stdout != ""

    - name: push
      command: git push origin master chdir="{{ projects_path }}"
      when: status_result.stdout != ""


