---
- hosts: 127.0.0.1
  vars:

  tasks:
    - name: upload with git-projects container
      command: >
        docker run --rm
        --volumes-from jenkins
        flemay/git-jenkins
        ./service.sh upload "{{ commit_msg }}"


