FROM ubuntu:14.04
ENV REFRESHED_AT 20141123
RUN apt-get update -qq && apt-get install -qqy curl
RUN curl https://get.docker.com/gpg | apt-key add -
RUN echo deb http://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
RUN apt-get update -qq && apt-get install -qqy iptables ca-certificates lxc openjdk-6-jdk git-core lxc-docker
