---
- hosts: 127.0.0.1
  vars:
    - docker_cmd: /usr/bin/docker
    - docker_run: "{{ docker_cmd }} run"
    - docker_build: "{{ docker_cmd }} build"
    - docker_remove: "{{ docker_cmd }} rm"
  tasks:
    - name: build image {{ item }}
      command: "{{ docker_build }} -t flemay/{{ item }} ../images/{{ item }}"
      with_items:
        - jenkins-data
        - git-projects
        - git-jenkins
        - jenkins

    - name: delete containers
      command: "{{ docker_remove }} -f {{ item }}"
      with_items:
        - jenkins-data
        - jenkins
      ignore_errors: yes

    - name: create jenkins data container
      command: "{{ docker_run }} --name jenkins-data flemay/jenkins-data"

    - name: pull projects from gihub into the data container
      command: "{{ docker_run }} --rm --volumes-from jenkins-data flemay/git-projects ./service.sh download"

    - name: create Jenkins container that has access to Docker deamon
      command: >
        {{ docker_run }} -p 8080:8080
        --name jenkins -d
        --volumes-from jenkins-data
        --volumes-from ansible-bootstrap
        -e DOCKER_HOST={{ lookup('env','DOCKER_HOST') }}
        -e DOCKER_TLS_VERIFY=1
        flemay/jenkins

    - name: display jenkins url
      debug: msg=http:{{ ansible_env.DOCKER_HOST }}
